name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Build projects if present
        run: |
          set -e

          echo "Verificando e construindo C214 (se existir)..."
          if [ -f "./C214/pom.xml" ]; then
            echo "Found C214/pom.xml -> building C214"
            mvn -f ./C214/pom.xml -B clean install
          else
            echo "C214/pom.xml não encontrado, pulando C214"
          fi

          echo "Verificando e construindo Aprendendo_test (se existir)..."
          if [ -f "./Aprendendo_test/pom.xml" ]; then
            echo "Found Aprendendo_test/pom.xml -> building Aprendendo_test"
            mvn -f ./Aprendendo_test/pom.xml -B clean install
          else
            echo "Aprendendo_test/pom.xml não encontrado, pulando Aprendendo_test"
          fi

      - name: Upload build artifacts (JARs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            C214/target/*.jar
            Aprendendo_test/target/*.jar

  teste:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests (if project exists)
        run: |
          set -e

          if [ -f "./Aprendendo_test/pom.xml" ]; then
            echo "Executando testes em Aprendendo_test..."
            cd ./Aprendendo_test
            mvn -B clean test site
          elif [ -f "./C214/pom.xml" ]; then
            echo "Aprendendo_test não encontrado — executando testes em C214..."
            cd ./C214
            mvn -B clean test site
          else
            echo "Nenhum pom.xml em Aprendendo_test ou C214 — pulando testes."
          fi

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-teste
          path: |
            Aprendendo_test/target/site/
            C214/target/site/

  notification:
    needs: teste
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for shell script
        run: |
          if [ -f "./scripts/shell.sh" ]; then
            chmod +x ./scripts/shell.sh
            echo "Permissão de execução aplicada em ./scripts/shell.sh"
          else
            echo "scripts/shell.sh não encontrado! Verifique o caminho."
            exit 1
          fi

      - name: Run notification script (entra em Aprendendo_test)
        run: |
          # passa o caminho preferencial (Aprendendo_test) para o script
          ./scripts/shell.sh ./Aprendendo_test
